services:
  my_unique_mariadb:
    image: mariadb:11.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "geochangesdb"
      MYSQL_USER: "new_user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=geochangesdb;User=new_user;Password=user_password"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
