# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  webapplication1:
    build:
      context: "/Users/jonasmoenpettersen/Documents/gruppekode/Gruppe12Sem3"
      dockerfile: "WebApplication1/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebApplication1.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/WebApplication1.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webapplication1:dev"
    ports: []
    volumes:
    - "/Users/jonasmoenpettersen/Documents/gruppekode/Gruppe12Sem3/WebApplication1:/app:rw"
    - "/Users/jonasmoenpettersen/Documents/gruppekode/Gruppe12Sem3:/src:rw"
    - "/Users/jonasmoenpettersen/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
